- hosts: all
  tasks:
    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: .env
        mode: '0644'

    - name: Create docker network
      community.docker.docker_network:
        name: app_network

    - name: Start redmine container
      community.docker.docker_container:
        env_file: .env
        image: 'redmine:latest'
        name: redmine
        restart_policy: always
        state: started
        networks:
          - name: app_network

    - name: Create Nginx config directory
      ansible.builtin.file:
        path: /etc/nginx
        state: directory
        mode: '0755'
      become: yes

    - name: Copy Nginx config
      ansible.builtin.copy:
        src: default.conf
        dest: /etc/nginx/default.conf
        mode: '0644'
      become: yes

    - name: Create SSL directory
      ansible.builtin.file:
        path: /etc/ssl
        state: directory
        mode: '0755'
      become: yes
    
    - name: Copy SSL certificates
      ansible.builtin.copy:
        src: "ssl/{{ item }}"
        dest: "/etc/ssl/{{ item }}"
        mode: '0644'
      loop:
        - cert.pem
        - key.pem
      become: yes

    - name: Start nginx container
      community.docker.docker_container:
        image: 'nginx'
        name: nginx-proxy
        ports:
          - 80:80
          - 443:443
        restart_policy: always
        state: started
        networks:
          - name: app_network
        volumes:
          - /etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - /etc/ssl/:/ssl/certs
