- hosts: all
  tasks:
    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: .env
        mode: '0644'

    - name: Create docker network
      community.docker.docker_network:
        name: app_network

    - name: Start redmine container
      community.docker.docker_container:
        env_file: .env
        image: 'redmine:latest'
        name: redmine
        restart_policy: always
        state: started
        networks:
          - name: app_network

- hosts: webservers
  roles:
    - datadog.datadog
  become: yes
