redmine_db_password: "{{ vault_redmine_db_password }}"
datadog_api_key: "{{ vault_datadog_api_key }}"
datadog_site: us5.datadoghq.com
datadog_checks:
  http_check:
    instances:
      - name: valman.info
        url: https://valman.info
